server.port: 1111
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/newdb
spring.datasource.username: root
spring.datasource.password: Rootpass12
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring:
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
